name: sts
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  shared_preferences: ^2.0.5
  flutter_neumorphic: ^3.1.0
  formz: ^0.4.0
  font_awesome_flutter: ^9.0.0
  package_info: ^2.0.0
  flutter_placeholder_textlines: ^1.0.4
  flutter_spinkit: ^5.0.0
  app_settings: ^4.1.0
  connectivity: ^3.0.3
  flutter_local_notifications: ^5.0.0+4
  get: ^4.1.4
  cached_network_image: ^3.0.0
  table_calendar: ^3.0.0
  date_picker_timeline: ^1.2.3
  measured_size: ^1.0.0
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^4.2.0
  flutter_datetime_picker: ^1.5.1

  # Firebase
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_storage: ^8.1.3

  # Change Icon and Splash launch
  flutter_launcher_icons: ^0.9.0
  splash_screen_view: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# Edit App icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

splash_screen_view:
  # Light theme splash screen
  background_image: "assets/images/splashscreen.png"
  image: assets/images/logo_white_transparent.png

  # Dark theme splash screen
  background_image_dark: "assets/images/splashscreen.png"
  image_dark: assets/images/logo_white_transparent.png

  android: true
  ios: true
  #web: false

  android_gravity: center
  ios_content_mode: center
  #web_image_mode: center

  fullscreen: true

  # info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    # Font for logo
    - family: HolidaySweetLovely
      fonts:
        - asset: assets/fonts/HolidaySweetLovely.ttf
    # Default font
    - family: Aileron
      fonts:
        - asset: assets/fonts/Aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/Aileron/Aileron-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 400
        - asset: assets/fonts/Aileron/Aileron-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/Aileron/Aileron-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/fonts/Aileron/Aileron-BlackItalic.otf
          weight: 900
          style: italic
